ObjectInformation/Controllers/ObjectRealtyController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NLog;
using ObjectInformation.DAL;
using ObjectInformation.DAL.Model;
using ObjectInformation.Models;
using PagedList;

namespace ObjectInformation.Controllers
{
    [Authorize]
    public class ObjectRealtyController : BaseController
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();

        public ActionResult Index()
        {
            List<ObjectRealty> objectRealties = ServiceObjectRealty.GetObjectRealties();
            ViewBag.ObjectProperty = db.ObjectProperties.ToList();
            ViewBag.Uploads = db.Uploads.ToList();
            return View(objectRealties);
        }

        public ActionResult AddObject(int objectRealtyId = 0)
        {
            ObjectRealty objectRealty = new ObjectRealty();

            if (objectRealtyId == 0)
            {
                objectRealty.CreateDate = DateTime.Now;
                objectRealty.CreateUser = User.Identity.Name;

                string msg;
                if (ServiceObjectRealty.AddObjectRealty(ref objectRealty, out msg))
                {
                  
                    ViewBag.ObjectPropertiesM =db.ObjectProperties.Where(w => w.ObjectRealtyId == objectRealty.ObjectRealtyId).ToList();
                    ViewBag.ObjectImage = db.Uploads.Where(w => w.ObjectRealtyId == objectRealty.ObjectRealtyId).ToList();
                    ViewBag.Properties = Service.GetProperties().Select(s => new SelectListItem() { Text = s.Name, Value = s.PropertyId.ToString() }).ToList();
                    ViewBag.ObjectRealtyPledgers = ServicePledgers.GetObjectRealtyPledgersByObjectId(0);
                      return View(objectRealty);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                objectRealty = db.ObjectRealties.Find(objectRealtyId);
                if (objectRealty != null)
                {
                    ViewBag.ObjectPropertiesM = db.ObjectProperties.Where(w => w.ObjectRealtyId == objectRealty.ObjectRealtyId).ToList();
                    ViewBag.ObjectImage = db.Uploads.Where(w => w.ObjectRealtyId == objectRealty.ObjectRealtyId).ToList();
                    ViewBag.Properties = Service.GetProperties().Select(s => new SelectListItem() { Text = s.Name, Value = s.PropertyId.ToString() }).ToList();
                    ViewBag.ObjectRealtyPledgers = ServicePledgers.GetObjectRealtyPledgersByObjectId(objectRealtyId);

                    return View(objectRealty);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
        }

        [HttpPost]
        public ActionResult AddObject(ObjectRealty objectRealty)
        {
            string msg;

            DateTime costDate;
            DateTime.TryParse(Request.Form["CostDate"], out costDate);
            objectRealty.CostDate = costDate;

            if (ServiceObjectRealty.UpdateObjectRealty(objectRealty, out msg))
            {
                return RedirectToAction("Index");
            }


            return View(objectRealty);
        }

        #region  РАБОТА со свойствами объекта
        [HttpGet]
        public JsonResult ViewForEditObjectProperty(int value)
        {
            var objectProperty = db.ObjectProperties.Where(w => w.ObjectPropertyId == value);

            return Json(objectProperty.Select(s => new { s.ObjectPropertyId, s.PropertyId, s.Value, s.ObjectRealtyId }).SingleOrDefault(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ModifyObjectProperty(string json)
        {
            try
            {
                dynamic data = JObject.Parse(json);

                ObjectProperty jObjectProperty = JsonConvert.DeserializeObject<ObjectProperty>(json, new Helper.MyDateTimeConverter());
                jObjectProperty.ObjectRealtyId = Convert.ToInt32(data.PropObjectRealtyId);


                ObjectProperty objectProperty = db.ObjectProperties.Find(jObjectProperty.ObjectPropertyId);
                if (objectProperty != null)
                {
                    objectProperty.PropertyId = jObjectProperty.PropertyId;
                    objectProperty.Value = jObjectProperty.Value;
                    objectProperty.ObjectRealtyId = jObjectProperty.ObjectRealtyId;
                    db.SaveChanges();
                }
                else
                {
                    db.ObjectProperties.Add(jObjectProperty);
                    db.SaveChanges();
                }
            }
            catch (Exception ex)
            {

            }

            return null;
        }

        [HttpPost]
        public ActionResult DeleteObjectProperty(int value = 0)
        {
            try
            {
                ObjectProperty objectProperty = db.ObjectProperties.Find(value);
                if (objectProperty != null)
                {
                    db.ObjectProperties.Remove(objectProperty);
                    db.SaveChanges();
                }

            }
            catch (Exception ex)
            {
            }
            return null;
        }
        #endregion

        #region РАБОТА С КАРТИНКАМИ
        [HttpGet]
        public JsonResult ViewForEditObjectImage(int value)
        {
            var uploads = db.Uploads.Where(w => w.UploadId == value);

            return Json(uploads.Select(s => new { s.UploadId, s.FileHeader, s.FileDescription }).SingleOrDefault(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public virtual ActionResult UploadImages(int objectId, int uploadId = 0)
        {
            try
            {

                Upload upload = new Upload();
                upload.ObjectRealtyId = objectId;
                upload.FileHeader = Request.Form["FileHeader"];
                upload.FileDescription = Request.Form["FileDescription"];
                upload.CreateDate = DateTime.Now;

                upload.DocumentType = db.DocumentTypes.First(f => f.DocumentTypeName == "Photo");
                upload.DocumentTypeId = upload.DocumentType.DocumentTypeId;
                upload.UploadId = uploadId;

                var file = Request.Files["FileUploadImage"];

                if (file == null || file.ContentLength == 0)
                    return Json(new { isUploaded = false, message = "Файл поврежден или пустой!" }, "text/html");

                if (Save(upload, file))
                    return Json(new { isUploaded = true, message = "Файл был загружен" }, "text/html");

                return Json(new { isUploaded = false, message = "При загрузке файла произошла ошибка!" }, "text/html");
            }
            catch (Exception ex)
            {
                string msg =
                   string.Format("Save, возникла ошибка: {0}", ex.Message);

                if (ex.InnerException != null)
                    msg += "\nInnerException: " + ex.InnerException.Message;

                if (ex.InnerException?.InnerException != null)
                    msg += "\nInnerException: " + ex.InnerException.InnerException.Message;

                logger.Error(msg);

                return Json(new { isUploaded = false, message = "При загрузке файла произошла ошибка!" }, "text/html");
            }
        }

        [HttpPost]
        public virtual ActionResult EditUpload(string json)
        {
            Upload upload = JsonConvert.DeserializeObject<Upload>(json);

            Service.EditPhoto(upload);

            return Json(null, "text/html");
        }

        [HttpPost]
        public ActionResult DeleteObjectImageRow(int value = 0)
        {
            try
            {
                Upload upload = db.Uploads.Find(value);
                if (upload != null)
                {
                    db.Uploads.Remove(upload);
                    db.SaveChanges();
                }

            }
            catch (Exception ex)
            {
            }
            return null;
        }
        #endregion

        #region РАБОТА С ФАЙЛАМИ
        [HttpGet]
        public JsonResult ViewForEditObjectDocument(int value)
        {
            var uploads = db.Uploads.Where(w => w.UploadId == value);

            return Json(uploads.Select(s => new { DocUploadId = s.UploadId, DocFileHeader = s.FileHeader, DocFileDescription = s.FileDescription, s.DocumentTypeId }).SingleOrDefault(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public virtual ActionResult UploadDocument(int objectId, int uploadId = 0)
        {
            Upload upload = new Upload();
            upload.ObjectRealtyId = objectId;
            upload.FileHeader = Request.Form["DocFileHeader"];
            upload.FileDescription = Request.Form["DocFileDescription"];
            upload.CreateDate = DateTime.Now;

            int DocTypeId = 3;
            Int32.TryParse(Request.Form["DocumentTypeId"].ToString(), out DocTypeId);

            upload.DocumentTypeId = DocTypeId;
            upload.DocumentType = db.DocumentTypes.First(f => f.DocumentTypeId == DocTypeId);


            upload.UploadId = uploadId;

            var file = Request.Files["FileUploadDoc"];

            if (file == null || file.ContentLength == 0)
                return Json(new { isUploaded = false, message = "Файл поврежден или пустой!" }, "text/html");

            if (Save(upload, file))
                return Json(new { isUploaded = true, message = "Файл был загружен" }, "text/html");

            return Json(new { isUploaded = false, message = "При загрузке файла произошла ошибка!" }, "text/html");
        }

        [HttpPost]

ObjectInformation/Views/ObjectRealty/Index.cshtml
@using System.Security.Policy
@using ObjectInformation.DAL.Model
@model List<ObjectInformation.DAL.Model.ObjectRealty>

@{
    ViewBag.Title = "Объекты";
}
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style type="text/css">
    .translatedDataTableRow {
        cursor: pointer;
        -webkit-transition-property: background-color;
        -webkit-transition-duration: 0.8451s;
        -webkit-transition-timing-function: ease-out;
    }
</style>

<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Home")">Главная</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Управление</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span style="color:black">Объекты</span>
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h1 class="page-title">
    Объекты
    <small>список объектов недвиджимости</small>
</h1>
<!-- END PAGE TITLE-->

<hr />
<a class="btn btn-primary" style="margin-top: 10px;" href="@Url.Action("AddObject", "ObjectRealty")">Добавить объект</a>

<table class="table table-striped table-bordered table-advance table-hover" style="margin-top:20px">
    <thead>
        <tr role="row">
            <th>#</th>
            <th>Тип</th>
            <th>Название</th>
            <th>Описание</th>
            <th>Цена</th>
            <th>Дата приобретения</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr class="odd parent">
                <td>@(i + 1)</td>
                <td>@Model[i].ObjectType.ObjectTypeName</td>
                <td>@Model[i].Name</td>
                <td>
                    @Model[i].Description<br />
                    <span class="badge badge-default">Адрес:</span>&nbsp
                    <span style="font-size: 11px">@Model[i].GetFullAddress()</span>
                </td>
                <td>
                    @Model[i].Cost <span class="badge badge-default">@Model[i].Currency.Name</span>
                </td>
                <td>
                    @string.Format("{0:dd.MM.yyyy}", Model[i].CostDate)
                    @if (Model[i].DateOfSale != null && Model[i].DateOfSale != DateTime.MinValue)
                    {
                        <span class="badge badge-danger">@string.Format("{0:dd.MM.yyyy}", Model[i].DateOfSale)</span>
                    }
                </td>
                <td>
                    <div class="btn-group  btn-group-solid">
                        <button type="button" class="btn blue dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            <i class="fa fa-ellipsis-horizontal"></i> Дейтсвие <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu" style="text-align: left">
                            <li><a href="/ObjectRealty/AddObject?objectRealtyId=@Model[i].ObjectRealtyId" class="edit-button">Редактировать</a></li>
                            <li><a href="/Task/Index?objectId=@Model[i].ObjectRealtyId">Список задач</a></li>
                            <li><a onclick="AppCity.DeleteRow('@Model[i].ObjectRealtyId', this) " class="delete-button">Удалить</a></li>
                        </ul>
                    </div>
                </td>
            </tr>

            <tr class="child">
                <td class="child" colspan="8">
                    <div class="row">
                        <div class="col-md-6">
                            <ul data-dtr-index="4">
                                @if ((List<ObjectProperty>)ViewBag.ObjectProperty != null)
                                {
                                    foreach (var item in ((List<ObjectProperty>)ViewBag.ObjectProperty).Where(w => w.ObjectRealtyId == Model[i].ObjectRealtyId))
                                    {
                                        <li data-dtr-index="3" data-dt-row="4" data-dt-column="3">
                                            <span class="badge badge-default dtr-title">@item.Property.Name</span>
                                            <span class="dtr-data">@item.Value @item.Property.Unit.Name</span>
                                        </li>
                                    }
                                }
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <ul class="list-inline blog-images">
                                @foreach (var image in ((List<Upload>)ViewBag.Uploads).Where(w => w.DocumentTypeId == 3 && w.ObjectRealtyId == Model[i].ObjectRealtyId))
                                {
                                    <li>
                                        <a class="fancybox-button" data-rel="fancybox-button" title="@Model[i].Name" href="@image.Path">
                                            <img alt="" src="@image.Path">
                                        </a>
                                    </li>
                                }
                            </ul>
                            <br style="clear: both" />
                            <ul class="list-inline blog-images">
                                @foreach (var image in ((List<Upload>)ViewBag.Uploads).Where(w => w.DocumentTypeId != 3 && w.ObjectRealtyId == Model[i].ObjectRealtyId))
                                {
                                    <li>
                                        <a class="fancybox-button" data-rel="fancybox-button" title="@Model[i].Name" href="@image.Path" target="_newTab">
                                            <img alt="" src="~/assets/global/img/file.png">
                                        </a>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>



@section Scripts {
    <script src="~/Scripts/Helper.js"></script>
}

ObjectInformation/Views/ObjectRealty/ObjectFiles.cshtml
@model List<ObjectInformation.DAL.Model.Upload>

<div class="images">
    @foreach (var file in Model)
    {
        <div class="fileWrap">
            <div>
                <a href="@Url.Action("SendFile", new { path = file.Path, fileName = file.FileName})"><i class="fas fa-arrow-down"></i></a>
                <span>@file.FileName</span>
                <button class="delBtn2" type="button" onclick="DeleteUpload(@file.UploadId)">X</button>
            </div>
            <div>
                <span>Тип документа: <b>@file.DocumentType.DocumentTypeName</b></span>
            </div>
        </div>
    }
</div>

<style>
    .fileWrap {
        position: relative;
        border: 1px solid black;
        padding: 10px;
    }

    .images {
        display: flex;
        flex-wrap: wrap; 
    }

    .delBtn2 {
        background-color: transparent;
        border: none;
        transition: 0.2s;
    }

    .delBtn2:hover {
        background-color: dimgray;
    }
</style>

ObjectInformation/Views/ObjectRealty/ObjectType.cshtml
@using System.Web.Mvc
@using System.Web.Mvc.Html
@using ObjectInformation.DAL.Model
@model ObjectType
@{
    ViewBag.Title = "Типы объектов";
}
<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Типы объектов <small>...</small>
</h3>

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Home")">Главная</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Управление</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span style="color: black">Типы объектов</span>
        </li>
    </ul>

    <div class="page-toolbar">
        <div class="btn-group pull-right">
            <button type="button" class="btn btn-fit-height grey-salt dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                Действия <i class="fa fa-angle-down"></i>
            </button>
            <ul class="dropdown-menu pull-right" role="menu">
                <li>
                    <a href="#" onclick="AppObjectType.GetModalWindowForEditandPopulate(null, this);">Добавить</a>
                </li>
                <li>
                    <a href="#">Импорт в Excel</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- END PAGE HEADER-->

<div class="row">
    <div class="col-md-12">

        <table class="table table-bordered table-advance table-hover table-striped" id="tableObjectTypes">
            <thead>
                <tr>
                    <th style="width: 5%">Номер</th>
                    <th>Наименование</th>
                    <th></th>
                </tr>
            </thead>
        </table>

        <br style="clear: both"/>
        @Html.Partial("ObjectType/_modifyObjectType")

    </div>
</div>

@section Scripts
{
    <script src="~/assets/plugins/AppObjectType.js"></script>

    <script>
        $(document).ready(function () {
            AppObjectType.init();
        });
    </script>
}

ObjectInformation/Views/ObjectRealty/Property.cshtml
@using System.Web.Mvc
@using System.Web.Mvc.Html
@using ObjectInformation.DAL.Model
@model Property
@{
    ViewBag.Title = "Свойства объектов";

    int? isErrorMessage = ViewBag.isErrorMessage;
    string message = ViewBag.message;
    List<Property> properties = (List<Property>)ViewBag.Properties;
}


<!-- BEGIN PAGE HEADER-->
<h3 class="page-title">
    Свойства объектов <small>...</small>
</h3>

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Home")">Главная</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="#">Управление</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span style="color: black">Свойства объектов</span>
        </li>
    </ul>

    <div class="page-toolbar">
        <div class="btn-group pull-right">
            <button type="button" class="btn btn-fit-height grey-salt dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                Действия <i class="fa fa-angle-down"></i>
            </button>
            <ul class="dropdown-menu pull-right" role="menu">
                <li>
                    <a href="#" onclick="AppProperty.GetModalWindowForEditandPopulate(null, this);">Добавить</a>
                </li>
                <li>
                    <a href="#">Импорт в Excel</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- END PAGE HEADER-->

<div class="row">
    <div class="col-md-12">

        <table class="table table-bordered table-advance table-hover table-striped" id="tableProperties">
            <thead>
                <tr>
                    <th>Номер</th>
                    <th>Наименование</th>
                    <th>Ед.измеренеия</th>
                    <th>Типы объектов</th>
                    <th></th>
                </tr>
            </thead>
        </table>

        @Html.Partial("Property/_modifyProperty")

    </div>
</div>

@section Scripts
{
<script src="~/assets/plugins/AppProperty.js"></script>

<script>
        $(document).ready(function () {
            AppProperty.init();
        });
</script>
}

ObjectInformation/Views/ObjectRealty/_PartialObjectPhotos.cshtml
@using ObjectInformation.DAL.Model
@model List<Upload>

<div class="imageWrapper">
    <div class="images">
        @foreach (Upload photo in Model)
        {
            <div style="position:relative">
                <button type="button" class="delBtn" onclick="DeleteUpload(@photo.UploadId)">X</button>
                <img width="70" height="70" src="@photo.Path" />
            </div>
        }
    </div>
</div>

<style>
    .imageWrapper {
        padding: 10px 30px 30px 30px;
        text-align: center;
    }

    .imageWrapper span {
        font-size: 25px;
    }

    .images {
        display: flex;
        flex-wrap: wrap;
    }

    .images div {
        margin: 10px;
    }

    .delBtn {
        z-index: 100;
        position: absolute;
        left: 100%;
        top: -15%;
        background-color: transparent;
        border: none;
        transition: 1s;
    }

    .delBtn:hover {
        background-color: dimgray;
    }
</style>